package com.yudha.hms.integration.bpjs.dto.erekammedis;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * BPJS eRekam Medis Record Completeness Report.
 *
 * Kelengkapan rekam medis (medical record completeness) reporting to BPJS.
 * Tracks documentation completeness for regulatory compliance as per Permenkes No. 24/2022.
 *
 * @author HMS Development Team
 * @version 1.0.0
 * @since 2025-01-20
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RecordCompletenessReport {

    /**
     * Report period start date (yyyy-MM-dd).
     */
    @JsonProperty("periodStart")
    private String periodStart;

    /**
     * Report period end date (yyyy-MM-dd).
     */
    @JsonProperty("periodEnd")
    private String periodEnd;

    /**
     * Organization/facility code.
     */
    @JsonProperty("organizationCode")
    private String organizationCode;

    /**
     * Organization name.
     */
    @JsonProperty("organizationName")
    private String organizationName;

    /**
     * Total number of encounters in period.
     */
    @JsonProperty("totalEncounters")
    private Integer totalEncounters;

    /**
     * Number of complete records.
     */
    @JsonProperty("completeRecords")
    private Integer completeRecords;

    /**
     * Number of incomplete records.
     */
    @JsonProperty("incompleteRecords")
    private Integer incompleteRecords;

    /**
     * Completeness percentage.
     */
    @JsonProperty("completenessPercentage")
    private Double completenessPercentage;

    /**
     * Breakdown by encounter type.
     */
    @JsonProperty("byEncounterType")
    private List<EncounterTypeBreakdown> byEncounterType;

    /**
     * Breakdown by completion status.
     */
    @JsonProperty("completenessDetails")
    private CompletenessDetails completenessDetails;

    /**
     * Incomplete record details.
     */
    @JsonProperty("incompleteRecordDetails")
    private List<IncompleteRecord> incompleteRecordDetails;

    /**
     * Report generation timestamp (ISO 8601 format).
     */
    @JsonProperty("generatedAt")
    private String generatedAt;

    /**
     * Report generated by (user ID).
     */
    @JsonProperty("generatedBy")
    private String generatedBy;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class EncounterTypeBreakdown {
        /**
         * Encounter type: rawat-jalan, rawat-inap, emergency.
         */
        @JsonProperty("encounterType")
        private String encounterType;

        /**
         * Total encounters of this type.
         */
        @JsonProperty("total")
        private Integer total;

        /**
         * Complete records.
         */
        @JsonProperty("complete")
        private Integer complete;

        /**
         * Incomplete records.
         */
        @JsonProperty("incomplete")
        private Integer incomplete;

        /**
         * Completeness percentage.
         */
        @JsonProperty("completenessPercentage")
        private Double completenessPercentage;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CompletenessDetails {
        /**
         * Records with patient demographics complete.
         */
        @JsonProperty("demographicsComplete")
        private Integer demographicsComplete;

        /**
         * Records with diagnosis documented (ICD-10).
         */
        @JsonProperty("diagnosisDocumented")
        private Integer diagnosisDocumented;

        /**
         * Records with procedures documented (ICD-9-CM).
         */
        @JsonProperty("proceduresDocumented")
        private Integer proceduresDocumented;

        /**
         * Records with medications documented.
         */
        @JsonProperty("medicationsDocumented")
        private Integer medicationsDocumented;

        /**
         * Records with lab results attached (if ordered).
         */
        @JsonProperty("labResultsAttached")
        private Integer labResultsAttached;

        /**
         * Records with radiology results attached (if ordered).
         */
        @JsonProperty("radiologyResultsAttached")
        private Integer radiologyResultsAttached;

        /**
         * Records with clinical notes (SOAP) documented.
         */
        @JsonProperty("clinicalNotesDocumented")
        private Integer clinicalNotesDocumented;

        /**
         * Records with discharge summary (for inpatients).
         */
        @JsonProperty("dischargeSummaryComplete")
        private Integer dischargeSummaryComplete;

        /**
         * Records with doctor's signature.
         */
        @JsonProperty("doctorSignaturePresent")
        private Integer doctorSignaturePresent;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class IncompleteRecord {
        /**
         * Encounter ID.
         */
        @JsonProperty("encounterId")
        private String encounterId;

        /**
         * Medical record number.
         */
        @JsonProperty("medicalRecordNumber")
        private String medicalRecordNumber;

        /**
         * Patient name.
         */
        @JsonProperty("patientName")
        private String patientName;

        /**
         * Encounter date (yyyy-MM-dd).
         */
        @JsonProperty("encounterDate")
        private String encounterDate;

        /**
         * Encounter type.
         */
        @JsonProperty("encounterType")
        private String encounterType;

        /**
         * Attending doctor.
         */
        @JsonProperty("attendingDoctor")
        private String attendingDoctor;

        /**
         * Missing elements (list of incomplete items).
         */
        @JsonProperty("missingElements")
        private List<String> missingElements;

        /**
         * Days since encounter (for timeliness tracking).
         */
        @JsonProperty("daysSinceEncounter")
        private Integer daysSinceEncounter;
    }
}
