package com.yudha.hms.laboratory.entity;

import com.yudha.hms.laboratory.constant.ReportStatus;
import com.yudha.hms.laboratory.constant.ReportType;
import com.yudha.hms.shared.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Lab Report Entity.
 *
 * Generated laboratory reports with PDF support.
 * Supports single test reports, cumulative reports, and trend analysis.
 * Includes digital signature and distribution tracking.
 *
 * @author HMS Development Team
 * @version 1.0.0
 * @since 2025-01-21
 */
@Entity
@Table(name = "lab_report", schema = "laboratory_schema", indexes = {
        @Index(name = "idx_lab_report_number", columnList = "report_number", unique = true),
        @Index(name = "idx_lab_report_type", columnList = "report_type"),
        @Index(name = "idx_lab_report_order", columnList = "order_id"),
        @Index(name = "idx_lab_report_patient", columnList = "patient_id"),
        @Index(name = "idx_lab_report_encounter", columnList = "encounter_id"),
        @Index(name = "idx_lab_report_status", columnList = "status"),
        @Index(name = "idx_lab_report_generated_at", columnList = "generated_at")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class LabReport extends BaseEntity {

    /**
     * Report number (unique identifier)
     */
    @Column(name = "report_number", nullable = false, unique = true, length = 50)
    private String reportNumber;

    // ========== Report Type ==========

    /**
     * Report type (SINGLE_TEST, CUMULATIVE, TREND_ANALYSIS, QUALITY_CONTROL, UTILIZATION)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "report_type", nullable = false, length = 50)
    private ReportType reportType;

    // ========== Order and Patient Reference ==========

    /**
     * Order ID (for single test reports)
     */
    @Column(name = "order_id")
    private UUID orderId;

    /**
     * Patient ID
     */
    @Column(name = "patient_id", nullable = false)
    private UUID patientId;

    /**
     * Encounter ID
     */
    @Column(name = "encounter_id")
    private UUID encounterId;

    // ========== Report Content ==========

    /**
     * Report title
     */
    @Column(name = "report_title", nullable = false, length = 500)
    private String reportTitle;

    /**
     * Report description
     */
    @Column(name = "report_description", columnDefinition = "TEXT")
    private String reportDescription;

    // ========== Date Range (for Cumulative/Trend Reports) ==========

    /**
     * Report start date
     */
    @Column(name = "report_start_date")
    private LocalDateTime reportStartDate;

    /**
     * Report end date
     */
    @Column(name = "report_end_date")
    private LocalDateTime reportEndDate;

    // ========== Report Generation ==========

    /**
     * Generated timestamp
     */
    @Column(name = "generated_at", nullable = false)
    @Builder.Default
    private LocalDateTime generatedAt = LocalDateTime.now();

    /**
     * Generated by user ID
     */
    @Column(name = "generated_by", nullable = false)
    private UUID generatedBy;

    // ========== Report Format ==========

    /**
     * Format (PDF, HTML, JSON)
     */
    @Column(name = "format", nullable = false, length = 50)
    @Builder.Default
    private String format = "PDF";

    /**
     * File path (where the report is stored)
     */
    @Column(name = "file_path", length = 500)
    private String filePath;

    /**
     * File size in KB
     */
    @Column(name = "file_size_kb")
    private Integer fileSizeKb;

    // ========== Report Status ==========

    /**
     * Status (DRAFT, FINAL, REVISED, CANCELLED)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    @Builder.Default
    private ReportStatus status = ReportStatus.DRAFT;

    /**
     * Finalized timestamp
     */
    @Column(name = "finalized_at")
    private LocalDateTime finalizedAt;

    // ========== Digital Signature ==========

    /**
     * Signed
     */
    @Column(name = "signed")
    @Builder.Default
    private Boolean signed = false;

    /**
     * Signed by user ID
     */
    @Column(name = "signed_by")
    private UUID signedBy;

    /**
     * Signed timestamp
     */
    @Column(name = "signed_at")
    private LocalDateTime signedAt;

    /**
     * Digital signature data
     */
    @Column(name = "digital_signature", columnDefinition = "TEXT")
    private String digitalSignature;

    // ========== Distribution ==========

    /**
     * Printed
     */
    @Column(name = "printed")
    @Builder.Default
    private Boolean printed = false;

    /**
     * Printed timestamp
     */
    @Column(name = "printed_at")
    private LocalDateTime printedAt;

    /**
     * Printed by user ID
     */
    @Column(name = "printed_by")
    private UUID printedBy;

    /**
     * Emailed
     */
    @Column(name = "emailed")
    @Builder.Default
    private Boolean emailed = false;

    /**
     * Emailed timestamp
     */
    @Column(name = "emailed_at")
    private LocalDateTime emailedAt;

    /**
     * Email recipients
     */
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "email_recipients")
    private List<String> emailRecipients;

    /**
     * Accessed by clinical staff
     */
    @Column(name = "accessed_by_clinical")
    @Builder.Default
    private Boolean accessedByClinical = false;

    /**
     * First accessed timestamp
     */
    @Column(name = "first_accessed_at")
    private LocalDateTime firstAccessedAt;

    // ========== Template ==========

    /**
     * Template ID
     */
    @Column(name = "template_id")
    private UUID templateId;

    /**
     * Template name
     */
    @Column(name = "template_name", length = 200)
    private String templateName;

    // ========== Letterhead ==========

    /**
     * Include letterhead
     */
    @Column(name = "include_letterhead")
    @Builder.Default
    private Boolean includeLetterhead = true;

    /**
     * Letterhead logo path
     */
    @Column(name = "letterhead_logo_path", length = 500)
    private String letterheadLogoPath;

    // ========== Additional Content ==========

    /**
     * Clinical interpretation
     */
    @Column(name = "clinical_interpretation", columnDefinition = "TEXT")
    private String clinicalInterpretation;

    /**
     * Recommendations
     */
    @Column(name = "recommendations", columnDefinition = "TEXT")
    private String recommendations;

    /**
     * Disclaimers
     */
    @Column(name = "disclaimers", columnDefinition = "TEXT")
    private String disclaimers;

    /**
     * Notes
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    // ========== Helper Methods ==========

    /**
     * Check if report is final
     */
    public boolean isFinal() {
        return status.isFinal();
    }

    /**
     * Check if report is signed
     */
    public boolean isSigned() {
        return Boolean.TRUE.equals(signed);
    }

    /**
     * Check if report has been printed
     */
    public boolean isPrinted() {
        return Boolean.TRUE.equals(printed);
    }

    /**
     * Check if report has been emailed
     */
    public boolean isEmailed() {
        return Boolean.TRUE.equals(emailed);
    }

    /**
     * Check if report has been accessed by clinical staff
     */
    public boolean isAccessedByClinical() {
        return Boolean.TRUE.equals(accessedByClinical);
    }

    /**
     * Mark as finalized
     */
    public void markFinalized() {
        this.status = ReportStatus.FINAL;
        this.finalizedAt = LocalDateTime.now();
    }

    /**
     * Mark as signed
     */
    public void markSigned(UUID signedBy, String digitalSignature) {
        this.signed = true;
        this.signedBy = signedBy;
        this.signedAt = LocalDateTime.now();
        this.digitalSignature = digitalSignature;
    }

    /**
     * Mark as printed
     */
    public void markPrinted(UUID printedBy) {
        this.printed = true;
        this.printedAt = LocalDateTime.now();
        this.printedBy = printedBy;
    }

    /**
     * Mark as emailed
     */
    public void markEmailed(List<String> recipients) {
        this.emailed = true;
        this.emailedAt = LocalDateTime.now();
        this.emailRecipients = recipients;
    }

    /**
     * Mark as accessed
     */
    public void markAccessed() {
        if (!Boolean.TRUE.equals(accessedByClinical)) {
            this.accessedByClinical = true;
            this.firstAccessedAt = LocalDateTime.now();
        }
    }
}
