package com.yudha.hms.integration.bpjs.dto.antreanrs;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BPJS Antrean RS Add Queue Request.
 *
 * Request to add new patient queue to BPJS system.
 *
 * @author HMS Development Team
 * @version 1.0.0
 * @since 2025-01-20
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AddQueueRequest {

    /**
     * Unique booking code generated by hospital.
     */
    @JsonProperty("kodebooking")
    private String kodebooking;

    /**
     * Patient type: "JKN" or "NON JKN".
     */
    @JsonProperty("jenispasien")
    private String jenispasien;

    /**
     * BPJS card number (empty if NON JKN).
     */
    @JsonProperty("nomorkartu")
    private String nomorkartu;

    /**
     * National ID (NIK).
     */
    @JsonProperty("nik")
    private String nik;

    /**
     * Patient phone number.
     */
    @JsonProperty("nohp")
    private String nohp;

    /**
     * Polyclinic code (BPJS subspecialist code).
     */
    @JsonProperty("kodepoli")
    private String kodepoli;

    /**
     * Polyclinic name.
     */
    @JsonProperty("namapoli")
    private String namapoli;

    /**
     * New patient flag: 1 (Yes), 0 (No).
     */
    @JsonProperty("pasienbaru")
    private Integer pasienbaru;

    /**
     * Medical record number.
     */
    @JsonProperty("norm")
    private String norm;

    /**
     * Examination date (yyyy-MM-dd).
     */
    @JsonProperty("tanggalperiksa")
    private String tanggalperiksa;

    /**
     * BPJS doctor code.
     */
    @JsonProperty("kodedokter")
    private Integer kodedokter;

    /**
     * Doctor name.
     */
    @JsonProperty("namadokter")
    private String namadokter;

    /**
     * Doctor's practice hours (e.g., "08:00-16:00").
     */
    @JsonProperty("jampraktek")
    private String jampraktek;

    /**
     * Visit type:
     * 1 (FKTP Referral),
     * 2 (Internal Referral),
     * 3 (Control),
     * 4 (Inter-hospital Referral).
     */
    @JsonProperty("jeniskunjungan")
    private Integer jeniskunjungan;

    /**
     * Referral/control number (empty if NON JKN).
     */
    @JsonProperty("nomorreferensi")
    private String nomorreferensi;

    /**
     * Queue number (e.g., "A-12").
     */
    @JsonProperty("nomorantrean")
    private String nomorantrean;

    /**
     * Queue number as integer.
     */
    @JsonProperty("angkaantrean")
    private Integer angkaantrean;

    /**
     * Estimated service time in milliseconds.
     */
    @JsonProperty("estimasidilayani")
    private Long estimasidilayani;

    /**
     * Remaining JKN quota.
     */
    @JsonProperty("sisakuotajkn")
    private Integer sisakuotajkn;

    /**
     * Total JKN quota.
     */
    @JsonProperty("kuotajkn")
    private Integer kuotajkn;

    /**
     * Remaining non-JKN quota.
     */
    @JsonProperty("sisakuotanonjkn")
    private Integer sisakuotanonjkn;

    /**
     * Total non-JKN quota.
     */
    @JsonProperty("kuotanonjkn")
    private Integer kuotanonjkn;

    /**
     * Information/notes for patient.
     */
    @JsonProperty("keterangan")
    private String keterangan;
}
